"""
Subset of ESCO (European Skills, Competences, Qualifications and Occupations)
taxonomy relevant to digital / IT / management roles.
"""

ESCO_SKILLS: dict[str, list[str]] = {
    "Sviluppo Software": [
        "Sviluppo applicazioni web",
        "Sviluppo applicazioni mobile",
        "Programmazione back-end",
        "Programmazione front-end",
        "Architettura software",
        "Sviluppo API REST",
        "Microservizi",
        "Test del software",
        "Revisione del codice",
        "Programmazione orientata agli oggetti",
        "Programmazione funzionale",
    ],
    "Linguaggi & Framework": [
        "Python",
        "Java",
        "JavaScript / TypeScript",
        "C / C++",
        "C#",
        "Go",
        "Rust",
        "Kotlin",
        "Swift",
        "PHP",
        "Ruby",
        "Scala",
        "React",
        "Angular",
        "Vue.js",
        "Node.js",
        "Django",
        "FastAPI",
        "Spring Boot",
        ".NET / ASP.NET",
    ],
    "Dati & AI": [
        "Analisi dei dati",
        "Data engineering",
        "Data warehousing",
        "Business intelligence",
        "Machine learning",
        "Deep learning",
        "Natural language processing",
        "Computer vision",
        "MLOps",
        "Statistica applicata",
        "SQL avanzato",
        "Big data (Spark, Hadoop)",
        "Visualizzazione dati",
    ],
    "Cloud & Infrastruttura": [
        "Amazon Web Services (AWS)",
        "Microsoft Azure",
        "Google Cloud Platform (GCP)",
        "Kubernetes",
        "Docker",
        "Terraform / Infrastructure as Code",
        "CI/CD (Jenkins, GitHub Actions)",
        "Site reliability engineering",
        "Networking",
        "Linux / Unix",
        "Virtualizzazione",
    ],
    "Sicurezza": [
        "Cybersecurity",
        "Penetration testing",
        "Gestione delle vulnerabilità",
        "Sicurezza delle applicazioni (OWASP)",
        "Gestione degli incidenti di sicurezza",
        "Crittografia",
        "Identity & Access Management",
        "Conformità normativa (GDPR, ISO 27001)",
    ],
    "Database": [
        "PostgreSQL",
        "MySQL / MariaDB",
        "Oracle Database",
        "Microsoft SQL Server",
        "MongoDB",
        "Redis",
        "Elasticsearch",
        "Cassandra",
        "Progettazione di database",
        "Ottimizzazione delle query",
    ],
    "UX / Design": [
        "User experience design",
        "User interface design",
        "Ricerca utente",
        "Prototipazione (Figma, Sketch)",
        "Accessibilità web",
        "Design system",
        "Usability testing",
    ],
